version: '3'

services:
    django:
        build: .
        container_name: "django"
        command: python3 manage.py runserver
        volumes:
            - .:/app/
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
            - CELERY_BROKER='redis://127.0.0.1:6379'
            - CELERY_BACKEND='redis://localhost:6379/0'
        depends_on:
            - pgdb
            - redis
        ports:
            - "8000:8000"
    celery:
        build: .
        command: celery -A core worker -l INFO
        volumes:
            - .:/app/
        depends_on:
            - django
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
              - POSTGRES_DB=postgres
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=postgres
        volumes:
              - ./postgresql/data:/var/lib/postgresql/data
              - ./postgresql/conf:/etc/postgresql/
